include:
  - local: "/includes/node.yml"
  - local: "/includes/docker.yml"
  - local: "/includes/rules.yml"
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
    ref: main

default:
  image: alpine:latest
#  tags:
#    - ADD_CUSTOM_TAG_HERE

variables:
  # TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${IMAGE_REPOSITORY}"


stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: canel2-front
    TAG: latest
  stage: docker-build
  extends:
    - .kaniko:build